CREATE TYPE "status" AS ENUM (
	'andamento',
	'concluido'
);

CREATE TYPE "unidade" AS ENUM (
	'peso',
	'unidade'
);

CREATE TABLE IF NOT EXISTS "usuarios" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nome" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL UNIQUE,
	"senha" VARCHAR(255) NOT NULL,
	"foto" VARCHAR(500),
	"bio" VARCHAR(255),
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "receitas" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nome" VARCHAR(255) NOT NULL,
	"descricao" VARCHAR(255),
	"user_id" INTEGER NOT NULL,
	"tempo_estimado_min" INTEGER,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "partes_producao" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"producao_id" INTEGER NOT NULL,
	"nome" VARCHAR(255) NOT NULL,
	"posicao" INTEGER NOT NULL,
	"concluida" BOOLEAN NOT NULL DEFAULT false,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "partes_receita" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"receita_id" INTEGER NOT NULL,
	"nome" VARCHAR(255) NOT NULL,
	"posicao" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "agulhas" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nome" VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "producoes_agulhas" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"producao_id" INTEGER NOT NULL,
	"agulha_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

CREATE UNIQUE INDEX "producoes_agulhas_unique"
ON "producoes_agulhas" ("producao_id", "agulha_id");

CREATE TABLE IF NOT EXISTS "producoes_novelo" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"producao_id" INTEGER NOT NULL,
	"nome" VARCHAR(255) NOT NULL,
	"cor" VARCHAR(255) NOT NULL,
	"peso" DECIMAL(10,3) NOT NULL,
	"comprimento" DECIMAL(10,3) NOT NULL,
	"quantidade_utilizada" DECIMAL(10,3) NOT NULL,
	"quantidade_unidade" UNIDADE NOT NULL,
	"custo_unidade" DECIMAL(10,2) NOT NULL,
	"custo_total" DECIMAL(10,2) NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "producoes_materiais" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"producao_id" INTEGER NOT NULL,
	"nome" VARCHAR(255) NOT NULL,
	"quantidade_utilizada" DECIMAL(10,3) NOT NULL,
	"quantidade_unidade" UNIDADE NOT NULL,
	"custo_unidade" DECIMAL(10,2) NOT NULL,
	"custo_total" DECIMAL(10,2) NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "receitas_materiais" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"receita_id" INTEGER NOT NULL,
	"nome" VARCHAR(255) NOT NULL,
	"quantidade_utilizada" DECIMAL(10,3) NOT NULL,
	"quantidade_unidade" UNIDADE NOT NULL,
	"custo_unidade" DECIMAL(10,2) NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "receitas_novelo" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"receita_id" INTEGER NOT NULL,
	"nome" VARCHAR(255) NOT NULL,
	"cor" VARCHAR(255) NOT NULL,
	"peso" DECIMAL(10,3) NOT NULL,
	"comprimento" DECIMAL(10,3) NOT NULL,
	"quantidade_utilizada" DECIMAL(10,3) NOT NULL,
	"quantidade_unidade" UNIDADE NOT NULL,
	"custo_unidade" DECIMAL(10,2) NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "receitas_agulhas" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"receita_id" INTEGER NOT NULL,
	"agulha_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

CREATE UNIQUE INDEX "receitas_agulhas_unique"
ON "receitas_agulhas" ("receita_id", "agulha_id");

CREATE TABLE IF NOT EXISTS "instrucoes_producao" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"producao_id" INTEGER NOT NULL,
	"parte_id" INTEGER,
	"posicao" INTEGER NOT NULL,
	"conteudo" TEXT NOT NULL,
	"quantidade_repeticoes" INTEGER NOT NULL DEFAULT 0,
	"concluida" BOOLEAN NOT NULL DEFAULT false,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "instrucoes_receita" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"receita_id" INTEGER NOT NULL,
	"parte_id" INTEGER,
	"posicao" INTEGER NOT NULL,
	"conteudo" TEXT NOT NULL,
	"quantidade_repeticoes" INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "fotos_receita" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"receita_id" INTEGER NOT NULL,
	"caminho" VARCHAR(500) NOT NULL,
	"posicao" INTEGER NOT NULL,
	"capa" BOOLEAN NOT NULL DEFAULT false,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "fotos_producao" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"producao_id" INTEGER NOT NULL,
	"caminho" VARCHAR(500) NOT NULL,
	"posicao" INTEGER NOT NULL,
	"capa" BOOLEAN NOT NULL DEFAULT false,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "producoes" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nome" VARCHAR(255) NOT NULL,
	"descricao" VARCHAR(255),
	"receita_id" INTEGER,
	"user_id" INTEGER NOT NULL,
	"status" STATUS NOT NULL DEFAULT 'andamento',
	"tempo_real" INTEGER NOT NULL DEFAULT 0,
	"iniciado_em" TIMESTAMP,
	"finalizado_em" TIMESTAMP,
	"custo_materiais" DECIMAL(10,2) NOT NULL DEFAULT 0,
	"valor_hora" DECIMAL(10,2),
	"custo_de_mao_obra" DECIMAL(10,2) NOT NULL DEFAULT 0,
	"margem_lucro" DECIMAL(5,2),
	"preco_sugerido" DECIMAL(10,2),
	PRIMARY KEY("id")
);

ALTER TABLE "receitas"
ADD FOREIGN KEY("id") REFERENCES "producoes"("receita_id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "usuarios"
ADD FOREIGN KEY("id") REFERENCES "receitas"("user_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "producoes"
ADD FOREIGN KEY("id") REFERENCES "partes_producao"("producao_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "producoes"
ADD FOREIGN KEY("id") REFERENCES "producoes_agulhas"("producao_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "agulhas"
ADD FOREIGN KEY("id") REFERENCES "producoes_agulhas"("agulha_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "producoes"
ADD FOREIGN KEY("id") REFERENCES "producoes_novelo"("producao_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "producoes"
ADD FOREIGN KEY("id") REFERENCES "producoes_materiais"("producao_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "receitas"
ADD FOREIGN KEY("id") REFERENCES "receitas_agulhas"("receita_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "agulhas"
ADD FOREIGN KEY("id") REFERENCES "receitas_agulhas"("agulha_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "receitas"
ADD FOREIGN KEY("id") REFERENCES "receitas_novelo"("receita_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "receitas"
ADD FOREIGN KEY("id") REFERENCES "receitas_materiais"("receita_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "receitas"
ADD FOREIGN KEY("id") REFERENCES "partes_receita"("receita_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "receitas"
ADD FOREIGN KEY("id") REFERENCES "instrucoes_receita"("receita_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "partes_receita"
ADD FOREIGN KEY("id") REFERENCES "instrucoes_receita"("parte_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "producoes"
ADD FOREIGN KEY("id") REFERENCES "instrucoes_producao"("producao_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "partes_producao"
ADD FOREIGN KEY("id") REFERENCES "instrucoes_producao"("parte_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "usuarios"
ADD FOREIGN KEY("id") REFERENCES "producoes"("user_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "producoes"
ADD FOREIGN KEY("id") REFERENCES "fotos_producao"("producao_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "receitas"
ADD FOREIGN KEY("id") REFERENCES "fotos_receita"("receita_id")
ON UPDATE NO ACTION ON DELETE CASCADE;